/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import library.LibraryString;
import render.BankComboboxModel;
import render.CaptchaComboboxModel;
import render.MoneyComboboxModel;
import render.TimeComboboxModel;

/**
 *
 * @author vuongluis
 */
public class NewApp extends javax.swing.JFrame {

    /**
     * Creates new form NewApp
     */
    private ArrayList<String> list = new ArrayList<>();
    
    public NewApp() {
        initComponents();
        ImageIcon image = new ImageIcon(this.getClass().getResource("/images/bitcoin.png"));
        this.setIconImage(image.getImage());
        this.setResizable(false);
        this.setTitle("Một phần của phần mềm bitcoinApp - Version1");
        this.cbMoney.setModel(new MoneyComboboxModel()); // Fix Import => no see error 
        this.cbTime.setModel(new TimeComboboxModel());
        this.cbCaptcha.setModel(new CaptchaComboboxModel());
        this.cbBank.setModel(new BankComboboxModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LeftPanel = new javax.swing.JPanel();
        cbMoney = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tfWebsite = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbCaptcha = new javax.swing.JComboBox();
        cbBank = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAHTML = new javax.swing.JTextArea();
        cbTime = new javax.swing.JComboBox();
        spSatoshi = new javax.swing.JSpinner();
        Button = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        chkRef = new javax.swing.JCheckBox();
        RightPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N

        jSplitPane1.setOneTouchExpandable(true);

        LeftPanel.setBackground(java.awt.Color.darkGray);
        LeftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xử Lý Dữ Liệu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
        LeftPanel.setPreferredSize(new java.awt.Dimension(405, 450));

        cbMoney.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BTC", " " }));
        cbMoney.setToolTipText("Ví dụ: BTC");
        cbMoney.setBorder(null);
        cbMoney.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Website:");

        tfWebsite.setToolTipText("Ví dụ: www.google.com.vn");
        tfWebsite.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        tfWebsite.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Satoshi:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Captcha:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thời gian:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rút tiền:");

        cbCaptcha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SM", "RC" }));
        cbCaptcha.setToolTipText("Ví dụ: BTC");
        cbCaptcha.setBorder(null);
        cbCaptcha.setPreferredSize(new java.awt.Dimension(50, 28));

        cbBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FaucetBOX", "ePay" }));
        cbBank.setToolTipText("Ví dụ: BTC");
        cbBank.setBorder(null);
        cbBank.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HTML:");

        tAHTML.setColumns(20);
        tAHTML.setLineWrap(true);
        tAHTML.setRows(5);
        tAHTML.setToolTipText("Ví dụ: \n<tr style=\"border-bottom: 5px solid white;\">\n\t<td style=\"background-color: #1c417f; color: white;\">BTC</td>\n\t<td style=\"color: red;\"><a \thref=\"http://www.siizo.com/?r=1Ash9Y2YGadx3FH2tQiYYiAskHcZ6jDSer\" \t\ttarget=\"_blank\">SIIZO</a></td>\n\t<td style=\"background-color: #87ceeb; color: white;\">60</td>\n\t<td style=\"background-color: #ff6a00; color: white;\">3</td>\n\t<td>SM</td>\n\t<td style=\"background-color: #35d13c; color: white;\">FaucetBOX</td>\n</tr>");
        tAHTML.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tAHTML);

        cbTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3" }));
        cbTime.setToolTipText("Ví dụ: 30");
        cbTime.setBorder(null);
        cbTime.setPreferredSize(new java.awt.Dimension(50, 28));

        spSatoshi.setPreferredSize(new java.awt.Dimension(29, 28));

        Button.setBackground(java.awt.Color.darkGray);

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setFocusable(false);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        Button.add(btnThem);

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btnSua.setText("Sữa");
        btnSua.setFocusable(false);
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button.add(btnSua);

        btnNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.setFocusable(false);
        btnNhapLai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapLai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button.add(btnNhapLai);

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hr.gif"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setFocusable(false);
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button.add(btnXoa);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loại tiền:");

        jPanel1.setBackground(java.awt.Color.darkGray);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DANH SÁCH TRANG WEBSITE GET SATOSHI/BTC");
        jPanel1.add(jLabel8);

        chkRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkRef.setForeground(new java.awt.Color(255, 255, 255));
        chkRef.setText("Ref");
        chkRef.setOpaque(false);
        chkRef.setPreferredSize(new java.awt.Dimension(81, 28));

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(tfWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkRef, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbBank, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCaptcha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(cbTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(spSatoshi, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(187, 187, 187))
                    .addComponent(cbMoney, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addComponent(Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spSatoshi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(LeftPanel);

        RightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray), "Dữ Liệu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        RightPanel.setPreferredSize(new java.awt.Dimension(396, 450));
        RightPanel.setLayout(new java.awt.BorderLayout());

        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbMain);

        RightPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(RightPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // Step 1
        String typeofMoney = (String) new MoneyComboboxModel().getElementAt(cbMoney.getSelectedIndex());
        if(tfWebsite.getText().isEmpty()){
            JOptionPane.showConfirmDialog(rootPane, "Vui lòng nhập đường link url");
            return ;
        }
        String url = tfWebsite.getText();
        String nameurl = new LibraryString().subString(url);
        if(chkRef.isSelected()){
            url = tfWebsite.getText()+"?r=1Ash9Y2YGadx3FH2tQiYYiAskHcZ6jDSer";
        }
        String satoshi = String.valueOf(spSatoshi.getValue());
        String time = (String) new TimeComboboxModel().getElementAt(cbTime.getSelectedIndex());
        String typeofCaptcha = (String) new CaptchaComboboxModel().getElementAt(cbCaptcha.getSelectedIndex());
        String withDrawModeny = (String) new BankComboboxModel().getElementAt(cbBank.getSelectedIndex());
        String outString = ""
        +"<tr style=\"border-bottom: 5px solid white;\">"
        +   "<td style=\"background-color: #1c417f; color: white;\">"+typeofMoney+"</td>"
        +    "<td style=\"color: red;\"><a href=\""+url+"\" target=\"_blank\">"+nameurl+"</a></td>"
        +    "<td style=\"background-color: #87ceeb; color: white;\">"+satoshi+"</td>"
        +    "<td style=\"background-color: #ff6a00; color: white;\">"+time+"</td>"
        +    "<td>"+typeofCaptcha+"</td>"
        +    "<td style=\"background-color: #35d13c; color: white;\">"+withDrawModeny+"</td>"
        +"</tr>";
        tAHTML.append(outString+"\n");
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cbBank;
    private javax.swing.JComboBox cbCaptcha;
    private javax.swing.JComboBox cbMoney;
    private javax.swing.JComboBox cbTime;
    private javax.swing.JCheckBox chkRef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSpinner spSatoshi;
    private javax.swing.JTextArea tAHTML;
    private javax.swing.JTable tbMain;
    private javax.swing.JTextField tfWebsite;
    // End of variables declaration//GEN-END:variables
}
