/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Bitcoin;
import controller.ControllerBitCoin;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;
import library.LibraryString;
import model.ModelBitCoin;
import render.BankComboboxModel;
import render.CaptchaComboboxModel;
import render.MoneyComboboxModel;
import render.TimeComboboxModel;

/**
 *
 * @author vuongluis
 */
public class NewApp extends javax.swing.JFrame {

    /**
     * Creates new form NewApp
     */
    private ArrayList<String> list = new ArrayList<>();
    private ControllerBitCoin controller;
    
    public NewApp() {
        initComponents();
        ImageIcon image = new ImageIcon(this.getClass().getResource("/images/bitcoin.png"));
        this.setIconImage(image.getImage());
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        this.setTitle("Một phần của phần mềm bitcoinApp - Version1");
        this.cbMoney.setModel(new MoneyComboboxModel()); // Fix Import => no see error 
        this.cbMoneyF.setModel(new MoneyComboboxModel()); // Fix Import => no see error 
        this.cbTime.setModel(new TimeComboboxModel());
        this.cbTimeF.setModel(new TimeComboboxModel());
        this.cbCaptcha.setModel(new CaptchaComboboxModel());
        this.cbBank.setModel(new BankComboboxModel());
        controller = new ControllerBitCoin(tbMain);
        controller.initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LeftPanel = new javax.swing.JPanel();
        cbMoney = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tfWebsite = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbCaptcha = new javax.swing.JComboBox();
        cbBank = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAHTML = new javax.swing.JTextArea();
        cbTime = new javax.swing.JComboBox();
        spSatoshi = new javax.swing.JSpinner();
        Button = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        chkRef = new javax.swing.JCheckBox();
        chkStatus = new javax.swing.JCheckBox();
        RightPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();
        pnSearch = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfWebsiteF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfSatoshiF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbTimeF = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbMoneyF = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1050, 495));

        jSplitPane1.setOneTouchExpandable(true);

        LeftPanel.setBackground(java.awt.Color.darkGray);
        LeftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xử Lý Dữ Liệu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
        LeftPanel.setPreferredSize(new java.awt.Dimension(405, 450));

        cbMoney.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BTC", " " }));
        cbMoney.setToolTipText("Ví dụ: BTC");
        cbMoney.setBorder(null);
        cbMoney.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Website:");

        tfWebsite.setForeground(new java.awt.Color(255, 0, 0));
        tfWebsite.setToolTipText("Ví dụ: www.google.com.vn");
        tfWebsite.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        tfWebsite.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Satoshi:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Captcha:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thời gian:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rút tiền:");

        cbCaptcha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SM", "RC" }));
        cbCaptcha.setToolTipText("Ví dụ: BTC");
        cbCaptcha.setBorder(null);
        cbCaptcha.setPreferredSize(new java.awt.Dimension(50, 28));

        cbBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FaucetBOX", "ePay" }));
        cbBank.setToolTipText("Ví dụ: BTC");
        cbBank.setBorder(null);
        cbBank.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HTML:");

        tAHTML.setColumns(20);
        tAHTML.setLineWrap(true);
        tAHTML.setRows(5);
        tAHTML.setToolTipText("");
        tAHTML.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tAHTML);

        cbTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3" }));
        cbTime.setToolTipText("Ví dụ: 30");
        cbTime.setBorder(null);
        cbTime.setPreferredSize(new java.awt.Dimension(50, 28));

        spSatoshi.setPreferredSize(new java.awt.Dimension(29, 28));

        Button.setBackground(java.awt.Color.darkGray);

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setFocusable(false);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        Button.add(btnThem);

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btnSua.setText("Sữa");
        btnSua.setFocusable(false);
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        Button.add(btnSua);

        btnNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.setFocusable(false);
        btnNhapLai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapLai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });
        Button.add(btnNhapLai);

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hr.gif"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setFocusable(false);
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        Button.add(btnXoa);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loại tiền:");

        jPanel1.setBackground(java.awt.Color.darkGray);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DANH SÁCH TRANG WEBSITE GET SATOSHI/BTC");
        jPanel1.add(jLabel8);

        chkRef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkRef.setForeground(new java.awt.Color(255, 255, 255));
        chkRef.setText("No Ref");
        chkRef.setOpaque(false);
        chkRef.setPreferredSize(new java.awt.Dimension(81, 28));

        chkStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkStatus.setForeground(new java.awt.Color(255, 255, 255));
        chkStatus.setText("Ok");
        chkStatus.setOpaque(false);
        chkStatus.setPreferredSize(new java.awt.Dimension(81, 28));

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBank, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCaptcha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(cbTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMoney, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(tfWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkRef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(spSatoshi, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(chkStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96))))
            .addComponent(Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spSatoshi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(LeftPanel);

        RightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray), "Dữ Liệu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        RightPanel.setPreferredSize(new java.awt.Dimension(396, 450));
        RightPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 300));

        tbMain.setAutoCreateRowSorter(true);
        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMainMousePressed(evt);
            }
        });
        tbMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMainKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbMain);

        RightPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnSearch.setBackground(new java.awt.Color(255, 255, 255));
        pnSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm thông tin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 2, 13))); // NOI18N
        pnSearch.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(516, 30));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 2));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Nhập tên website:");
        jPanel2.add(jLabel9);

        tfWebsiteF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        tfWebsiteF.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel2.add(tfWebsiteF);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setText("Số Satoshi");
        jPanel2.add(jLabel10);

        tfSatoshiF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        tfSatoshiF.setPreferredSize(new java.awt.Dimension(100, 24));
        jPanel2.add(tfSatoshiF);

        pnSearch.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Chọn mốc thời gian:");
        jPanel3.add(jLabel11);

        cbTimeF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn mốc thời gian --" }));
        cbTimeF.setMinimumSize(new java.awt.Dimension(56, 24));
        jPanel3.add(cbTimeF);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("Chọn loại tiền:");
        jPanel3.add(jLabel12);

        cbMoneyF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn loại tiền --" }));
        cbMoneyF.setMinimumSize(new java.awt.Dimension(56, 24));
        jPanel3.add(cbMoneyF);

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 102, 102));
        jCheckBox1.setText("Paying");
        jPanel3.add(jCheckBox1);

        pnSearch.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel4.add(btnSearch);

        pnSearch.add(jPanel4);

        RightPanel.add(pnSearch, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(RightPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // Step 1
        String typeofMoney = (String) new MoneyComboboxModel().getElementAt(cbMoney.getSelectedIndex());
        if(tfWebsite.getText().isEmpty()){
            JOptionPane.showConfirmDialog(rootPane, "Vui lòng nhập đường link url");
            return ;
        }
        String url = tfWebsite.getText();
        String nameurl = new LibraryString().subString(url);
        if(chkRef.isSelected()){
            url = tfWebsite.getText();
        }else{
            url = tfWebsite.getText()+"?r=1Ash9Y2YGadx3FH2tQiYYiAskHcZ6jDSer";
        }
        String satoshi = String.valueOf(spSatoshi.getValue());
        String time = (String) new TimeComboboxModel().getElementAt(cbTime.getSelectedIndex());
        String typeofCaptcha = (String) new CaptchaComboboxModel().getElementAt(cbCaptcha.getSelectedIndex());
        String withDrawModeny = (String) new BankComboboxModel().getElementAt(cbBank.getSelectedIndex());
        String outString = ""
        +"<tr>"+"\n"
        +    "<td style=\"text-align:center;background-color:#1c417f;color:white;\">"+typeofMoney+"</td>"+"\n"
        +    "<td style=\"text-align:center;color:red;\"><a style=\"text-decoration:none;\" href=\""+url+"\" target=\"_blank\">"+nameurl+"</a></td>"+"\n"
        +    "<td style=\"text-align:center;background-color:#87ceeb;color:white;\">"+satoshi+"</td>"+"\n"
        +    "<td style=\"text-align:center;background-color:#ffbaa0;color:white;\">"+time+"</td>"+"\n"
        +    "<td style=\"text-align:center;background-color:#fd7488;color:white;\">"+typeofCaptcha+"</td>"+"\n"
        +    "<td style=\"text-align:center;background-color:#35d13c;color:white;\">"+withDrawModeny+"</td>"+"\n"
        +"</tr>"+"\n"
        + "<tr style=\"height:1px;\"><td></td></tr>"+"\n";
        tAHTML.append(outString+"\n");
        /** Add data from filling out the form into data **/
        Bitcoin bitcoin = new Bitcoin(0, typeofMoney, url, satoshi, time, typeofCaptcha, withDrawModeny,false);
        if(controller.addItem(bitcoin)>0){
            JOptionPane.showConfirmDialog(new NewApp(),"Thêm mới thành công","Thông báo",JOptionPane.WARNING_MESSAGE);
            this.resetForm();
        }else{
            JOptionPane.showConfirmDialog(new NewApp(),"Thêm mới thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tbMainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMainKeyReleased
        this.setForm();
    }//GEN-LAST:event_tbMainKeyReleased

    private void tbMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMainMousePressed
        this.setForm();
    }//GEN-LAST:event_tbMainMousePressed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        // TODO add your handling code here:
        this.resetForm();
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tbMain.getSelectedRow();
        if(row >= 0){
            int id = (Integer)controller.getValueAt(row, 0);
            if(controller.deleteItem(id,row) > 0){
                JOptionPane.showConfirmDialog(new NewApp(), "Xóa thành công","Thông báo",JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showConfirmDialog(new NewApp(), "Xóa thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showConfirmDialog(new NewApp(), "Vui lòng chọn dòng để xóa","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = tbMain.getSelectedRow();
        if(row >= 0){
            int id = (Integer)controller.getValueAt(row, 0);
            String typeofMoney = (String) new MoneyComboboxModel().getElementAt(cbMoney.getSelectedIndex());
            String url = new ModelBitCoin().getItem(id).getUrl();
            String satoshi = String.valueOf((Integer)spSatoshi.getValue());
            String time = (String)new TimeComboboxModel().getElementAt(cbTime.getSelectedIndex());
            String typeofCaptcha = (String)new CaptchaComboboxModel().getElementAt(cbCaptcha.getSelectedIndex());
            String withDrawMoney = (String)new BankComboboxModel().getElementAt(cbBank.getSelectedIndex());
            Boolean status = chkStatus.isSelected();
            // writting to ease to fix not hard
            Bitcoin bitcoin = new Bitcoin(id, typeofMoney, url, satoshi, time, typeofCaptcha, withDrawMoney,status);
            if(controller.editItem(bitcoin,row) > 0){
                JOptionPane.showConfirmDialog(new NewApp(), "Cập nhật thành công","Thông báo",JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showConfirmDialog(new NewApp(), "Cập nhật thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showConfirmDialog(new NewApp(), "Vui lòng chọn dòng để cập nhật","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        TableRowSorter sorter = new TableRowSorter(tbMain.getModel());
        tbMain.setRowSorter(sorter);
        
        ArrayList<RowFilter<AbstractTableModel,Object>> alFilter = new ArrayList<>();
        
        String uWebsite = tfWebsiteF.getText();
        RowFilter<AbstractTableModel,Object> filterWebsite = RowFilter.regexFilter(uWebsite, 0);
        
        String uSatoshi = tfSatoshiF.getText();
        RowFilter<AbstractTableModel,Object> filterSatoshi = RowFilter.regexFilter(uSatoshi, 1);
        
        alFilter.add(filterWebsite);
        alFilter.add(filterSatoshi);
        
        RowFilter<AbstractTableModel,Object> filterAnd = RowFilter.andFilter(alFilter);
        sorter.setRowFilter(filterAnd);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cbBank;
    private javax.swing.JComboBox cbCaptcha;
    private javax.swing.JComboBox cbMoney;
    private javax.swing.JComboBox<String> cbMoneyF;
    private javax.swing.JComboBox cbTime;
    private javax.swing.JComboBox<String> cbTimeF;
    private javax.swing.JCheckBox chkRef;
    private javax.swing.JCheckBox chkStatus;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnSearch;
    private javax.swing.JSpinner spSatoshi;
    private javax.swing.JTextArea tAHTML;
    private javax.swing.JTable tbMain;
    private javax.swing.JTextField tfSatoshiF;
    private javax.swing.JTextField tfWebsite;
    private javax.swing.JTextField tfWebsiteF;
    // End of variables declaration//GEN-END:variables

    private void setForm() {
        int row = tbMain.getSelectedRow();
        int id = Integer.parseInt(tbMain.getValueAt(row, 0).toString());
        Bitcoin object = new ModelBitCoin().getItem(id);
        cbMoney.setModel(new MoneyComboboxModel((String) tbMain.getValueAt(row, 1)));
        tfWebsite.setText((String) tbMain.getValueAt(row, 2));
        tfWebsite.setToolTipText(object.getUrl());
        spSatoshi.setValue(Integer.parseInt((String) tbMain.getValueAt(row, 3)));
        cbTime.setModel(new TimeComboboxModel(String.valueOf(tbMain.getValueAt(row, 4))));
        cbCaptcha.setModel(new CaptchaComboboxModel((String) tbMain.getValueAt(row, 5))); // writting hard => it 's difficult to fix
        cbBank.setModel(new BankComboboxModel((String) tbMain.getValueAt(row, 6)));
        String outString = ""
        +"<tr>"+"\n"
        +    "<td style=\"text-align:center;background-color:#1c417f;color:white;\">"+tbMain.getValueAt(row, 1)+"</td>"+"\n"
        +    "<td style=\"text-align:center;color:red;\"><a style=\"text-decoration:none;\" href=\""+object.getUrl()+"\" target=\"_blank\">"+tbMain.getValueAt(row, 2)+"</a></td>"+"\n"
        +    "<td style=\"text-align:center;background-color:#87ceeb;color:white;\">"+tbMain.getValueAt(row, 3)+"</td>"+"\n"
        +    "<td style=\"text-align:center;background-color:#ffbaa0;color:white;\">"+tbMain.getValueAt(row, 4)+"</td>"+"\n"
        +    "<td style=\"text-align:center;background-color:#fd7488;color:white;\">"+tbMain.getValueAt(row, 5)+"</td>"+"\n"
        +    "<td style=\"text-align:center;background-color:#35d13c;color:white;\">"+tbMain.getValueAt(row, 6)+"</td>"+"\n"
        +"</tr>"+"\n"
        + "<tr style=\"height:1px;\"><td></td></tr>"+"\n";
        tAHTML.setText(outString);
    }
    private void resetForm(){
        cbMoney.setModel(new MoneyComboboxModel());
        tfWebsite.setText("");
        spSatoshi.setValue(0);
        cbTime.setModel(new TimeComboboxModel());
        cbCaptcha.setModel(new CaptchaComboboxModel());
        cbBank.setModel(new BankComboboxModel());
        tAHTML.setText("");
    }
}
